name: amarjit  # This is the workflow name shown in GitHub Actions tab

on:
  push:
    branches: [main]  # space after colon is important

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: greetings
        run: echo "hello world"
